### ISSUE TITLE
[Lake][DuckDB] Production tables data is getting deprecated if CSV data is deleted and refetched

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1042]
How to reproduce:
- go trough etl raw update flow
- delete csv files
- go trough etl raw update flow again and you should see that the deleted data from CSVs are duplicated inside the production tables

**Comment by idiom-bytes** [comment]
**When it comes to the current PR written:**
1. Our systems are not "smart". If you do what you're describing, you're breaking any sync.
2. If you delete data from CSV, there are no expectations that Raw or ETL tables will be updated.
3. GQLDF is meant to be a "dumb system". It's role is just to update the CSVs and then make sure the lake is up-to-date/syncd.

**The current PR will therefore not be merged because .**

When it comes to Sync, and the work that can be done to avoid duplicates:
- There is a potential edge case where data already exists.
- GQLDF is run to be updated so it can write new records to CSV + DuckDB
- CSV is at 0, but DuckDB has rows up-to 100
- When CSV goes to be updated, it resumes from 0, but DuckDB isn't clamped to 100 so it will experience duplicate records
- Because there are already records in DuckDB Raw Tables, the records won't be properly handled/clamped, and we'll end up with duplicates

**This still needs to be completed.**
