### ISSUE TITLE
[Lake][DuckDB] Fix bronze tables start and end date filter calculation

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1046]
In the current implementation the start and end date for the bronze tables is wrong, and here is why:
- the calculation is done once and it is the same for all the table which is wrong, the calculation should be done for each bronze table just like for each raw table
- the start time is the lowest timestamp from all the highest timestamp values from each **etl table**
- the end time is the lowest timestamp from all the highest timestamp values from each **raw table**

Proposed solution:
- calculate start and end date for each bronze table individually
- start time should be the highest timestamp from the current bronze table
- end time should be the highest timestamp from the corresponding raw table

**Comment by idiom-bytes** [comment]
```
the calculation is done once and it is the same for all the table which is wrong, the calculation should be done for each bronze table just like for each raw table
```
This is not wrong.
The tables have already been processed up-to the same time.
They do not have to be recalculated individually.

It is very different than how CSVs process information.
Raw Update
Input: GQL Data
Output: CSV + DB Tables

ETL Update
Input: DB Tables
Output: DB Tables

It isn't wrong because in the ETL step, all data has already been processed up-to the same date.

**Comment by idiom-bytes** [comment]
Closing this ticket
