### ISSUE TITLE
[Bug, plots] When I re-save any py files, it auto-pops up new plots

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1205]
**Describe the bug**

In one console, I have `pdr sim_plots` running. Since I've got it going, it's popped a plot window into my browser (good).

Then if I make any changes to any py file, it will open a _new_ plot window in my browser. This is annoying. It shouldn't open a new plot window. It should simply refresh the current one.

Related: 
- the following issue was recently completed: [#1144](https://github.com/oceanprotocol/pdr-backend/issues/1144) "[Sim_plots, UX] When 'pdr sim_plots' is run, it should automatically pop into browser"
- before it, we didn't have the problem that _this_ issue describes
- but after that issue was done, now the plots are over-zealous
- what we want is a happy medium: it should automatically pop _one_ plot into the browser, but not more

**Comment by trentmc** [comment]
My default browser is chrome (on Macos)

**Comment by KatunaNorbert** [comment]
Thanks that helped me to reproduce it, I changed my default browser to Chrome same with Firefox. Interestingly if default browser Safari than the issue doesn't occur, that's why a haven't seen it before

**Comment by KatunaNorbert** [comment]
I inspected the issue and couldn't find a nice way to fix it so here are the possible solutions:
- Enable turning debug mode on/off
Now we have debug mode enable by default, which makes everything run again once something changes in the code, which then triggers the window.open() method and that's why whenever something is saved a new tab is opened.
If we disable debugging than the app is not going to refresh on code change, which is a downside while working on new futures, but no new tabs.

- Removing the window opening by default
Probably the cleanest solution to just remove the functionality or only enable

- Combination of solutions above
We could use a combination of solutions from above like this: Disable debugging mode by default and add window.open functionality, this way window will open but wont trigger new tabs because of dash running on non debug mode. If debug mode is enabled than don't trigger the window.open, this way if you are running it you have to copy the url for the first time but then on reload no new windows are going to appear.

**Comment by KatunaNorbert** [comment]
That is going to solve the issue for non debug mode, but for debug mode the issue is still going to occur, that's why I suggested the last solution
