### ISSUE TITLE
Generate Python Script for Predictoor Analytics Raw Transaction Data

### ISSUE THREAD

**Issue by ChristianCasazza** [oceanprotocol/pdr-backend#359]
**Is your feature request related to a problem? Please describe.**
Create a Python script to execute the following [query](https://v4.subgraph.sapphire-mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A++predictPredictions+%28%0A++++where%3A+%7B%0A++++++slot_%3A+%7B%0A++++++++predictContract%3A+%220x18f54cc21b7a2fdd011bea06bba7801b280e3151%22%2C%0A++++++++slot_gt%3A+1696118400%2C+slot_lt%3A+1699401600%0A++++++%7D%0A++++%7D%0A++++skip%3A+0%2C+first%3A+1000%2C+%0A++%29+%7B%0A++++id%0A++++timestamp%0A++++user+%7B%0A++++++++id%0A++++%7D%0A++++stake%0A++++payout+%7B%0A++++++++payout%0A++++++++trueValue%0A++++++++predictedValue%0A++++%7D%0A++++slot+%7B%0A++++++slot%0A++++++predictContract+%7B%0A++++++++token+%7B%0A++++++++++name%0A++++++++%7D%0A++++++%7D%0A++++%7D%0A%7D%0A%7D)

The query will produce a dataset for a particular query with the schema predictionID, epoch, timestamp, stake, wallet address, payout, trueValue, and predicted value

**Describe the solution you'd like**
The script should produce CSV files for each feed. They can originally be manually consolidated together, and aggregation can be automated into the script later.

**Additional context**
The goal is to support this [epic ](https://github.com/oceanprotocol/pdr-analytics/issues/1). We want to use the subgraphs to create a raw source dataset of all predictions so that all analytics can be conducted downstream with tools better optimized for column-level queries.

**Comment by trentmc** [comment]
This issue was partly done via [PR#374](https://github.com/oceanprotocol/pdr-backend/pull/374).

Then, [this comment](https://github.com/oceanprotocol/pdr-backend/pull/374#issuecomment-1834582454) laid out the follow-up plan. 

There are now several utility tools in the CLI for predictoor data.

The "follow-up plan" has been further refined. Now, issue [#447](https://github.com/oceanprotocol/pdr-backend/issues/447) is the "main" plan for a "well-structured lake & analytics". 

Closing _this_ issue.
