### ISSUE TITLE
[Bug][Lake] PanicException when running pdr lake

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/pdr-backend#663]
Running locally in virtualenv with `polars==0.20.10`, path exported and all settings done. When doing `pdr lake my_ppss.yaml development` i get a PanicException. Same error happens for sim, as it uses lake. When running tests, I get no exceptions.

I suspect this is due to the pairs/publishing part, where I probably have some null values in the df and polars can't handle the joins like that. I assume the rest of the team has more data or other configured/published pairs, which is why this only happens to me. Either way, this case should be treated and I shouldn't get such a ... *panicky* error, but rather be warned somehow. We should get to the bottom of this for usability and UX.

I am attaching a screenshot of the error:
<img width="1094" alt="Screenshot 2024-02-22 at 1 00 48 PM" src="https://github.com/oceanprotocol/pdr-backend/assets/4101015/a9172060-2eb1-4c26-b747-53f6c83c9c3f">

I base my suppositions ref. null values on this StackOverflow question:
https://stackoverflow.com/questions/75631703/polars-arr-to-struct-throws-pyo3-runtime-panicexception-not-implemented-for

**Comment by idiom-bytes** [comment]
I spent some time reviewing this.
1. This is happening in the ohlcv factory
2. I have nuked all of my data and am able to re-run from the start, and continue to incrementally fetch the rest of the data without easily reproducing this
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/9826dc4b-ffb7-4b64-b0be-27c2a2db4d0e)

```
I suspect this is due to the pairs/publishing part, where I probably have some null values in the df and polars can't handle the joins like that. 
```
3. Yes, I'm led to believe that what it's happening, is that in the ohlcv, there are different data_sources (i.e. ETH-USDT_5m, BTC-USDT_5m) and when that data is being joined, some of the records are missing.

```
I assume the rest of the team has more data or other configured/published pairs, which is why this only happens to me. 
```
4. I don't think the team has any other configuration/pairs that are done in a special way. I think our first order of business would be to save/share your parquet files, such that we can explore the state of it and where the data is having issues.

I agree with you that a less "panicky" error would be preferred... but polars is panicky sometimes for the right reason.

`Not implemented` to me, is telling me that perhaps there are columns missing. Or some assumption that is made in code, is not translating correctly to the merge_ohlcv join that's taking place here.

Example:
```
BTC data has ohclv
ETH data has ohv
```

So, the step we should take here **is debug and (1) understand what your data looks like inside, and what's the problem that's taking place when trying to get merged_ohlcv.**

So please, share your ohlcv parquet files and m_ppss, such that we can try to reproduce this issue/understand what's happening with the data.

The second thing we can try to do, is (2) add some functionality to "drop records" from a st_date across multiple ohlcv datasets (BTC-5m,ETH-5m), or a single dataset (BTC-5m) and re-process them. This doesn't actually fix the problem that caused (1), but would allow you to more easily manage the lake.

```
Running locally in virtualenv with polars==0.20.10, path exported and all settings done. When doing pdr lake my_ppss.yaml development i get a PanicException. Same error happens for sim, as it uses lake. When running tests, I get no exceptions.
```
Tests that are running get_merged_olhcv_df() must do so with local/test data rather than lake data.

I don't think this is a version thing. Perhaps a ccxt error with how some data is being fetched. But... I believe it could perhaps be w/ using partial ohlcv configuration... Such as `BTC ohlcv` params and `ETH cv` params inside ppss.yaml that is leading to parquet files with weird columns, perhaps missing ones (such as timestamp), leading to errors while joining.

```
Not implemented seems like a straightforward error message to me... it's impossible to do. You can't just do a join on = expected_column
```

Please try sharing your parquet files rather than deleting them, so we can look further into this. A simple query into the head() of each dataframe you're trying to merge might give you the answer you are looking for.

**Comment by calina-c** [comment]
It's not happening anymore for me and nobody else can reproduce. I'm closing this and reopening if it appears again.
