### ISSUE TITLE
[SimEngine] Update data layer from pickling to duckdb

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#852]
1. Update serialization from pickle, to storying data in duckdb
2. Read from duckdb to feed into streamlit

**Comment by calina-c** [comment]
Closed due to issue with DuckDB not supporting concurrency. For now, pickling keeps being the best solution, but in the future we can tech spike other sql alternatives that fully support concurrent access, allowing multiple sims to be run at once.

I did manage to design code for the loading and unloading of np arrays into a database that supports BLOBs. If we ever go that route again, I've kept the essential code in a gist: https://gist.github.com/calina-c/79d7294b42080fe581a81e00ced6f587
